# Generated by Django 4.2.5 on 2023-11-12 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Full Name")),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Position in Lab"),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "profession",
                    models.CharField(max_length=100, verbose_name="Profession"),
                ),
                (
                    "degrees",
                    models.CharField(
                        max_length=200, verbose_name="Degrees/Certifications"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Staff",
                "verbose_name_plural": "Lab Staff",
                "ordering": ["name"],
            },
        ),
    ]
