# Generated by Django 4.2.5 on 2023-10-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BRU', 'Brucellosis'), ('MYC', 'Mycobacteria Bovina'), ('LEP', 'Leptospirosis'), ('RAB', 'Rabia'), ('FIE', 'Fiebre Aftosa')], max_length=3)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
            ],
        ),
    ]
