# Generated by Django 4.2.5 on 2023-11-13 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ("created_by",),
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Client Account",
            ),
            preserve_default=False,
        ),
    ]
