# Generated by Django 4.2.5 on 2023-10-01 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labservices', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='selected_diagnostics',
        ),
        migrations.AddField(
            model_name='client',
            name='selected_diagnostics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='labservices.diagnosticservice'),
        ),
    ]
