# Generated by Django 4.2.5 on 2023-10-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labservices', '0001_initial'),
        ('client', '0002_remove_client_converted_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='selected_diagnostics',
            field=models.ManyToManyField(related_name='clients_requests', to='labservices.diagnosticservice'),
        ),
    ]
