# Generated by Django 4.2.5 on 2023-10-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labservices', '0001_initial'),
        ('lead', '0002_lead_converted_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='selected_diagnostics',
            field=models.ManyToManyField(related_name='leads', to='labservices.diagnosticservice'),
        ),
    ]
