# Generated by Django 4.2.5 on 2023-10-01 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labservices', '0001_initial'),
        ('lead', '0003_lead_selected_diagnostics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='selected_diagnostics',
        ),
        migrations.AddField(
            model_name='lead',
            name='selected_diagnostics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='labservices.diagnosticservice'),
        ),
    ]
